# Generated by Django 5.2.14 on 2026-05-17 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=60, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta",
                "verbose_name_plural": "Etiquetas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=170, unique=True, verbose_name="Slug"
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "game_system",
                    models.CharField(max_length=100, verbose_name="Sistema de juego"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREPARING", "Preparando"),
                            ("ACTIVE", "Activa"),
                            ("FINISHED", "Finalizada"),
                        ],
                        default="PREPARING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Pública"), ("PRIVATE", "Privada")],
                        default="PUBLIC",
                        max_length=20,
                        verbose_name="Visibilidad",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="campaigns/covers/",
                        verbose_name="Imagen de portada",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directed_campaigns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Director/a",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="campaigns",
                        to="campaigns.tag",
                        verbose_name="Etiquetas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaña",
                "verbose_name_plural": "Campañas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DIRECTOR", "Director"),
                            ("PLAYER", "Jugador"),
                            ("SPECTATOR", "Espectador"),
                        ],
                        default="PLAYER",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INVITED", "Invitado"),
                            ("ACCEPTED", "Aceptado"),
                            ("REJECTED", "Rechazado"),
                        ],
                        default="ACCEPTED",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de unión"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="campaigns.campaign",
                        verbose_name="Campaña",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participación",
                "verbose_name_plural": "Participaciones",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "campaign"),
                        name="unique_user_campaign_participation",
                    )
                ],
            },
        ),
    ]
