# Generated by Django 5.2.14 on 2026-05-18 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MmSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('summary', models.TextField(blank=True, verbose_name='Resumen')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha programada')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración estimada (minutos)')),
                ('status', models.CharField(choices=[('PLANNED', 'Planificada'), ('PLAYED', 'Jugada'), ('CANCELLED', 'Cancelada')], default='PLANNED', max_length=20, verbose_name='Estado')),
                ('fictional_location', models.CharField(blank=True, max_length=200, verbose_name='Localización ficticia')),
                ('director_notes', models.TextField(blank=True, verbose_name='Notas del director')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='campaigns.campaign', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['scheduled_at', 'created_at'],
            },
        ),
    ]
