# Generated by Django 5.2.14 on 2026-05-18 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('resource_type', models.CharField(choices=[('MAP', 'Mapa'), ('IMAGE', 'Imagen'), ('LINK', 'Enlace'), ('DOCUMENT', 'Documento'), ('NOTE', 'Nota')], default='NOTE', max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='Archivo')),
                ('external_url', models.URLField(blank=True, verbose_name='URL externa')),
                ('visible_to_players', models.BooleanField(default=False, verbose_name='Visible para jugadores')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='campaigns.campaign', verbose_name='Campaña')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-created_at'],
            },
        ),
    ]
